nessie:
  image:
    repository: localhost:32531/nessie-unstable
    tag: latest
    pullPolicy: Always

  nodeSelector:
    kubernetes.io/hostname: node-dedicated-0

  versionStoreType: JDBC

  jdbc:
    jdbcUrl: jdbc:postgresql://nessie-postgresql-hl:5432/nessie
    secret:
      name: nessie-creds
      username: postgres_user
      password: postgres_password

  catalog:
    enabled: true
    iceberg:
      defaultWarehouse: lakehouse
      warehouses:
      - name: lakehouse
        location: hdfs:///lakehouse

  advancedConfig:
    quarkus:
      jaxb:
        enable: true
    nessie:
      catalog:
        service:
          hdfs:
            resources-config: /opt/hadoop/conf/core-site.xml

  extraVolumes:
  - name: hdfs-config
    configMap:
      name: nessie-hdfs
      optional: false

  extraVolumeMounts:
  - mountPath: /opt/hadoop/conf
    name: hdfs-config
    readOnly: true

postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: nessie
        username: nessie
        password: nessie
        database: nessie

  primary:
    livenessProbe:
      enabled: false
    resourcePreset: medium
    persistence:
      enabled: false
    nodeSelector: &node_selector
      kubernetes.io/hostname: node-dedicated-0
