apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds
data:
  postgres_user: {{ "nessie" | b64enc | quote }}
  postgres_password: {{ "nessie" | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ "admin" | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ "miniopass" | b64enc | quote }}
